### ISSUE TITLE
node 4 support with babel?

### ISSUE THREAD

**Issue by axe312ger** [philbooth/bfj#50]
Hey Phil,

I understand that adding babel takes efford and writing hoopy with es6 classes is neat, but your module is awesome and solves serious issues regarding big json files.

But node 4 is still in LTS and people (like myself 😅 ) are forced to still support it.

![](https://github.com/nodejs/LTS/raw/master/schedule.png)

Are there any options to reintroduce node 4 support?

The https://babeljs.io/repl/ shows that https://github.com/philbooth/hoopy would only have about 10 lines of extra code and still keeps readability for the build file.

I can help if you want :)

All the best,
Benedikt

**Comment by philbooth** [comment]
I'm definitely happy to do something about this.

The thing that hoopy really needs from 6+ is the `Proxy` object, so that it can trap array index access using `[0]` etc. Can that be shimmed or whatever via Babel?

If not, maybe I should keep a separate release branch for node 4, which reverts back to plain-old-arrays and manually manages the overflow/grow logic.

**Comment by axe312ger** [comment]
Argh damn, `Proxy` is not supported by Babel :/

**Comment by philbooth** [comment]
No probs. It shouldn't be too hard to revert back to the pre-hoopy logic in a node 4 branch, although I haven't properly looked yet.

**Comment by axe312ger** [comment]
A node 4 branch would be delicious <3

**Comment by macrozone** [comment]
just ran into this: ReferenceError: Proxy is not defined

using meteor, which still needs node 4

**Comment by philbooth** [comment]
I finally found some time to get round to this and have published a new package, `bfj-node4` to npm. I'll keep the version numbers in sync between that and the normal `bfj` package, so that the two have feature parity version-for-version.

If you want the src, it's in a `node-4` branch in this repo.

Let me know if you get any problems!
