### ISSUE TITLE
Does bfj support pause and resuming of the streaming emitter?

### ISSUE THREAD

**Issue by ashleydavis** [philbooth/bfj#58]
Hi @philbooth 

I'm currently implementing streaming file support for my open source project [Data-Forge](https://github.com/data-forge/data-forge-js).

I've done this already for CSV using Para Parse and I'm looking to implement JSON next. Was hoping to use your library but I'm not sure if it supports pausing and resuming of the streaming emitter?  If not is that something that you can easily add?

I need this because once an object is deserialized from the stream I don't want the stream to continue reading until the Data-Forge user requests the next item. So I'd like to be able to pause the stream until that happens.

Papa Parse supports this for its streaming CSV deserialization. To see how they do it look at their [docs](http://papaparse.com/docs) and read the `step` section.

Thanks!

**Comment by philbooth** [comment]
There is a `pause` method on the emitter returned by `bfj.eventify`, is that any good for you? You can look at `streamify` for usage.

If you want it on one of the higher-level methods it's easy enough to expose it there too.

**Comment by ashleydavis** [comment]
I'm actually using the emitter returned by the `walk` function.

```
const emitter = bfj.walk(fileInputStream);
```

It doesn't seem to have a pause function. Am I looking in the wrong place?

**Comment by philbooth** [comment]
Nope, the `walk` emitter is not decorated with a `pause` method at the moment, it's just special sauce for `eventify` because I needed it to eliminate out-of-memory errors over there.

I can add one, but I might not have time to do it until after Christmas now as there's other stuff I want to work on. If you need it quicker than that you're welcome to add one yourself, and I can help out with some pointers on implementing it and answer any questions you have.

**Comment by ashleydavis** [comment]
There's no urgency. I'm current porting Data-Forge to TypeScript and at the same time would like to bring streaming online, but I'm not going to publish it for a month or two.

Would love to see it in there though so I can move ahead with using it. Please let me know how you go!

**Comment by philbooth** [comment]
@ashleydavis, I took a stab at implementing this in a4cd0e0, available in current `master`. I haven't published it in a release yet because I wanted external validation that it works as expected before drawing attention to it in the readme etc. So if you get a chance to play with it, let me know how it goes.

Usage:

```js
const emitter = bfj.walk(stream)

// To pause:
const resume = emitter.pause()

// To resume:
resume()
```

**Comment by ashleydavis** [comment]
I've copied master into my project. Seems to work ok!

Thanks. Let me know when you have published so I can update my project.

**Comment by philbooth** [comment]
Done! Version `5.2.0`.
